[welcome-message]

# Welcome Message master switch
# true = enabled
# false = disabled
enabled = true

# Welcome message type
# chat = Chat message
# tip = Tip message
# toast = Toast message
type = "chat"

# Title of Toast message
# Effective only when message_type is 3
title = "Welcome Title"

# Welcome message text
# You can use ..........
text = "Welcome Text"

# Wait before welcome message in seconds
wait_before = 55
