[welcome_message]

# Welcome message type
# 0 = Disable Welcome Message
# 1 = Chat message
# 2 = Tip message
# 3 = Toast message
# 4 = Title message
# 5 = Popup message
type = 1

# Header of Toast or Title message
# Effective only when type is 3 (Toast) or 4 (Title)
header = "Welcome Header"

# Welcome message body
# You can use ..........
body = "Welcome message"

# Wait before welcome message in seconds.
# Valid values are between 0 and 10.
# 0 disables wait_before.
wait_before = 0
