[welcome_message]
# Welcome message type
# 0 = Disable Welcome Message
# 1 = Chat message
# 2 = Tip message
# 3 = Toast message
type = 1

# Title of Toast message
# Effective only when message_type is 3
title = "Welcome Title"

# Welcome message text
# You can use ..........
text = "Welcome Text"
