[welcome_message]

# Welcome Message master switch
# true = enabled
# false = disabled
enabled = true

# Welcome message type
# chat = Chat message
# tip = Tip message
# toast = Toast message
# popup = Popup message
type = "chat"

# Title of Toast message
# Effective only when type is toast
title = "Welcome Title"

# Welcome message text
# You can use ..........
text = "Welcome Text"

# Wait before welcome message in seconds.
# Valid values are between 0 and 10.
# 0 disables wait_before.
wait_before = 0
