[welcome_message]

# Welcome message type
# Valid values are between 0 and 5.
# 0 = Disable Welcome Message
# 1 = Chat
# 2 = Tip
# 3 = Popup
# 4 = Toast
# 5 = Title
# 6 = Form
type = 6

# Toast or Title message header
# Effective only when type is 3 (Toast) or 4 (Title)
header = "Welcome Header"

# Welcome message body
# You can use ..........
body = "Welcome message"

# Wait before welcome message in seconds.
# Valid values are between 0 and 10.
# 0 disables waiting.
wait_before = 0
